project:
  type: book

book:
  title: "Бессонница, Аквариум и Все мои самоубийства"
  author: "Александра Булгакова"
  chapters:

    - _main.Rmd

format:
  pdf:
    toc-depth: 2
    documentclass: scrreprt
    mainfont: Arial
    papersize: a5paper




